import { test } from 'node:test'
import assert from 'node:assert/strict'
import { attend, buy, buySet, initialEconomy, mission, rewardOutfit, setQuote, unlocked, validateEconomy } from '../src/lib/economyCore.ts'
const catalog=[...initialEconomy().owned.map(id=>({id,price:0})),{id:'chair',price:20,setId:'pink'},{id:'mirror',price:30,setId:'pink'},{id:'locked',price:1,unlock:{type:'streak' as const,value:3}}]
const funded=()=>({...initialEconomy(),points:100,earned:100})
test('출석은 같은 날·과거 날짜 중복 없이 7일째만 +50',()=>{let s=initialEconomy();for(let i=1;i<=7;i++)s=attend(s,`2026-10-0${i}`);assert.equal(s.points,85);assert.equal(s.streak,7);assert.equal(attend(s,'2026-10-07'),s);assert.equal(attend(s,'2026-10-01'),s);s=attend(s,'2026-10-09');assert.equal(s.streak,1);assert.equal(s.bestStreak,7)})
test('새 코디만 하루 세 번; 미션은 저장 후 하루 한 번',()=>{let s=initialEconomy();assert.equal(mission(s,'2026-10-09'),s);s=rewardOutfit(s,'a','2026-10-09');assert.equal(rewardOutfit(s,'a','2026-10-09'),s);s=rewardOutfit(s,'b','2026-10-09');s=rewardOutfit(s,'c','2026-10-09');assert.equal(rewardOutfit(s,'d','2026-10-09'),s);assert.equal(s.points,30);s=mission(s,'2026-10-09');assert.equal(s.points,60);assert.equal(mission(s,'2026-10-09'),s)})
test('레벨 증가 시 한 번만 보너스',()=>{let s={...initialEconomy(),xp:90};s=rewardOutfit(s,'a','2026-10-09');assert.equal(s.points,30);assert.equal(rewardOutfit(s,'a','2026-10-09'),s)})
test('구매는 한 번만 차감; 잔액 부족/잠금 구매 실패 시 원본 유지',()=>{const s=funded();const n=buy(s,catalog,'chair');assert.equal(n.points,80);assert.equal(buy(n,catalog,'chair'),n);assert.equal(s.points,100);assert.throws(()=>buy(initialEconomy(),catalog,'chair'),/INSUFFICIENT/);assert.throws(()=>buy(s,catalog,'locked'),/LOCKED/)})
test('세트는 미보유만 15% 할인, 완성 보너스 한 번',()=>{let s=buy(funded(),catalog,'chair');assert.equal(setQuote(s,catalog,'pink').price,26);s=buySet(s,catalog,'pink');assert.equal(s.points,69);assert.equal(buySet(s,catalog,'pink'),s);assert.deepEqual(s.completedSets,['pink'])})
test('출석 조건은 최고 연속 출석으로 해금 유지',()=>{let s=initialEconomy();for(let i=1;i<=3;i++)s=attend(s,`2026-10-0${i}`);s=attend(s,'2026-10-06');assert.equal(unlocked(s,catalog[7]),true)})
test('백업 round-trip 및 변조된 구조, 음수, 알 수 없는 아이템, 버전 거절',()=>{const s=funded();assert.deepEqual(validateEconomy(JSON.parse(JSON.stringify(s)),catalog),s);for(const bad of [{...s,points:-1},{...s,points:NaN},{...s,version:2},{...s,owned:[...s.owned,'nope']},{...s,rewards:{'bad':['x']}},{...s,owned:[...s.owned,s.owned[0]]}])assert.throws(()=>validateEconomy(bad,catalog))})
